import pandas as pd
from datetime import datetime, date

mylist = [
    {
        "symbol": "HAS",
        "quarterlyEarnings": [
            {
                "fiscalDateEnding": "2023-06-30",
                "reportedDate": "2023-08-03",
                "reportedEPS": "0.49",
                "estimatedEPS": "0.57",
                "surprise": "-0.08",
                "surprisePercentage": "-14.0351",
            },
            {
                "fiscalDateEnding": "2023-03-31",
                "reportedDate": "2023-04-27",
                "reportedEPS": "0.01",
                "estimatedEPS": "0.01",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2022-12-31",
                "reportedDate": "2023-02-16",
                "reportedEPS": "1.31",
                "estimatedEPS": "1.29",
                "surprise": "0.02",
                "surprisePercentage": "1.5504",
            },
            {
                "fiscalDateEnding": "2022-09-30",
                "reportedDate": "2022-10-18",
                "reportedEPS": "1.42",
                "estimatedEPS": "1.52",
                "surprise": "-0.1",
                "surprisePercentage": "-6.5789",
            },
            {
                "fiscalDateEnding": "2022-06-30",
                "reportedDate": "2022-07-19",
                "reportedEPS": "1.15",
                "estimatedEPS": "0.94",
                "surprise": "0.21",
                "surprisePercentage": "22.3404",
            },
            {
                "fiscalDateEnding": "2022-03-31",
                "reportedDate": "2022-04-19",
                "reportedEPS": "0.57",
                "estimatedEPS": "0.61",
                "surprise": "-0.04",
                "surprisePercentage": "-6.5574",
            },
            {
                "fiscalDateEnding": "2021-12-31",
                "reportedDate": "2022-02-07",
                "reportedEPS": "1.21",
                "estimatedEPS": "0.88",
                "surprise": "0.33",
                "surprisePercentage": "37.5",
            },
            {
                "fiscalDateEnding": "2021-09-30",
                "reportedDate": "2021-10-26",
                "reportedEPS": "1.96",
                "estimatedEPS": "1.69",
                "surprise": "0.27",
                "surprisePercentage": "15.9763",
            },
            {
                "fiscalDateEnding": "2021-06-30",
                "reportedDate": "2021-07-26",
                "reportedEPS": "1.05",
                "estimatedEPS": "0.47",
                "surprise": "0.58",
                "surprisePercentage": "123.4043",
            },
            {
                "fiscalDateEnding": "2021-03-31",
                "reportedDate": "2021-04-27",
                "reportedEPS": "1",
                "estimatedEPS": "0.65",
                "surprise": "0.35",
                "surprisePercentage": "53.8462",
            },
            {
                "fiscalDateEnding": "2020-12-31",
                "reportedDate": "2021-02-08",
                "reportedEPS": "1.27",
                "estimatedEPS": "1.14",
                "surprise": "0.13",
                "surprisePercentage": "11.4035",
            },
            {
                "fiscalDateEnding": "2020-09-30",
                "reportedDate": "2020-10-26",
                "reportedEPS": "1.88",
                "estimatedEPS": "1.63",
                "surprise": "0.25",
                "surprisePercentage": "15.3374",
            },
            {
                "fiscalDateEnding": "2020-06-30",
                "reportedDate": "2020-07-27",
                "reportedEPS": "0.02",
                "estimatedEPS": "0.23",
                "surprise": "-0.21",
                "surprisePercentage": "-91.3043",
            },
            {
                "fiscalDateEnding": "2020-03-31",
                "reportedDate": "2020-04-29",
                "reportedEPS": "0.57",
                "estimatedEPS": "0.58",
                "surprise": "-0.01",
                "surprisePercentage": "-1.7241",
            },
            {
                "fiscalDateEnding": "2019-12-31",
                "reportedDate": "2020-02-11",
                "reportedEPS": "1.24",
                "estimatedEPS": "0.91",
                "surprise": "0.33",
                "surprisePercentage": "36.2637",
            },
            {
                "fiscalDateEnding": "2019-09-30",
                "reportedDate": "2019-10-22",
                "reportedEPS": "1.84",
                "estimatedEPS": "2.21",
                "surprise": "-0.37",
                "surprisePercentage": "-16.7421",
            },
            {
                "fiscalDateEnding": "2019-06-30",
                "reportedDate": "2019-07-23",
                "reportedEPS": "0.78",
                "estimatedEPS": "0.5",
                "surprise": "0.28",
                "surprisePercentage": "56",
            },
            {
                "fiscalDateEnding": "2019-03-31",
                "reportedDate": "2019-04-23",
                "reportedEPS": "0.21",
                "estimatedEPS": "-0.11",
                "surprise": "0.32",
                "surprisePercentage": "290.9091",
            },
            {
                "fiscalDateEnding": "2018-12-31",
                "reportedDate": "2019-02-08",
                "reportedEPS": "1.33",
                "estimatedEPS": "1.67",
                "surprise": "-0.34",
                "surprisePercentage": "-20.3593",
            },
            {
                "fiscalDateEnding": "2018-09-30",
                "reportedDate": "2018-10-22",
                "reportedEPS": "1.93",
                "estimatedEPS": "2.23",
                "surprise": "-0.3",
                "surprisePercentage": "-13.4529",
            },
            {
                "fiscalDateEnding": "2018-06-30",
                "reportedDate": "2018-07-23",
                "reportedEPS": "0.48",
                "estimatedEPS": "0.29",
                "surprise": "0.19",
                "surprisePercentage": "65.5172",
            },
            {
                "fiscalDateEnding": "2018-03-31",
                "reportedDate": "2018-04-23",
                "reportedEPS": "0.1",
                "estimatedEPS": "0.33",
                "surprise": "-0.23",
                "surprisePercentage": "-69.697",
            },
            {
                "fiscalDateEnding": "2017-12-31",
                "reportedDate": "2018-02-07",
                "reportedEPS": "2.3",
                "estimatedEPS": "1.8",
                "surprise": "0.5",
                "surprisePercentage": "27.7778",
            },
            {
                "fiscalDateEnding": "2017-09-30",
                "reportedDate": "2017-10-23",
                "reportedEPS": "2.09",
                "estimatedEPS": "1.94",
                "surprise": "0.15",
                "surprisePercentage": "7.732",
            },
            {
                "fiscalDateEnding": "2017-06-30",
                "reportedDate": "2017-07-24",
                "reportedEPS": "0.53",
                "estimatedEPS": "0.46",
                "surprise": "0.07",
                "surprisePercentage": "15.2174",
            },
            {
                "fiscalDateEnding": "2017-03-31",
                "reportedDate": "2017-04-24",
                "reportedEPS": "0.43",
                "estimatedEPS": "0.38",
                "surprise": "0.05",
                "surprisePercentage": "13.1579",
            },
            {
                "fiscalDateEnding": "2016-12-31",
                "reportedDate": "2017-02-06",
                "reportedEPS": "1.64",
                "estimatedEPS": "1.27",
                "surprise": "0.37",
                "surprisePercentage": "29.1339",
            },
            {
                "fiscalDateEnding": "2016-09-30",
                "reportedDate": "2016-10-17",
                "reportedEPS": "2.03",
                "estimatedEPS": "1.74",
                "surprise": "0.29",
                "surprisePercentage": "16.6667",
            },
            {
                "fiscalDateEnding": "2016-06-30",
                "reportedDate": "2016-07-18",
                "reportedEPS": "0.41",
                "estimatedEPS": "0.39",
                "surprise": "0.02",
                "surprisePercentage": "5.1282",
            },
            {
                "fiscalDateEnding": "2016-03-31",
                "reportedDate": "2016-04-18",
                "reportedEPS": "0.38",
                "estimatedEPS": "0.24",
                "surprise": "0.14",
                "surprisePercentage": "58.3333",
            },
            {
                "fiscalDateEnding": "2015-12-31",
                "reportedDate": "2016-02-08",
                "reportedEPS": "1.39",
                "estimatedEPS": "1.3",
                "surprise": "0.09",
                "surprisePercentage": "6.9231",
            },
            {
                "fiscalDateEnding": "2015-09-30",
                "reportedDate": "2015-10-19",
                "reportedEPS": "1.58",
                "estimatedEPS": "1.52",
                "surprise": "0.06",
                "surprisePercentage": "3.9474",
            },
            {
                "fiscalDateEnding": "2015-06-30",
                "reportedDate": "2015-07-20",
                "reportedEPS": "0.33",
                "estimatedEPS": "0.29",
                "surprise": "0.04",
                "surprisePercentage": "13.7931",
            },
            {
                "fiscalDateEnding": "2015-03-31",
                "reportedDate": "2015-04-20",
                "reportedEPS": "0.21",
                "estimatedEPS": "0.08",
                "surprise": "0.13",
                "surprisePercentage": "162.5",
            },
            {
                "fiscalDateEnding": "2014-12-31",
                "reportedDate": "2015-02-09",
                "reportedEPS": "1.22",
                "estimatedEPS": "1.21",
                "surprise": "0.01",
                "surprisePercentage": "0.8264",
            },
            {
                "fiscalDateEnding": "2014-09-30",
                "reportedDate": "2014-10-20",
                "reportedEPS": "1.46",
                "estimatedEPS": "1.45",
                "surprise": "0.01",
                "surprisePercentage": "0.6897",
            },
            {
                "fiscalDateEnding": "2014-06-30",
                "reportedDate": "2014-07-21",
                "reportedEPS": "0.36",
                "estimatedEPS": "0.36",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2014-03-31",
                "reportedDate": "2014-04-21",
                "reportedEPS": "0.14",
                "estimatedEPS": "0.1",
                "surprise": "0.04",
                "surprisePercentage": "40",
            },
            {
                "fiscalDateEnding": "2013-12-31",
                "reportedDate": "2014-02-10",
                "reportedEPS": "1.12",
                "estimatedEPS": "1.22",
                "surprise": "-0.1",
                "surprisePercentage": "-8.1967",
            },
            {
                "fiscalDateEnding": "2013-09-30",
                "reportedDate": "2013-10-21",
                "reportedEPS": "1.31",
                "estimatedEPS": "1.29",
                "surprise": "0.02",
                "surprisePercentage": "1.5504",
            },
            {
                "fiscalDateEnding": "2013-06-30",
                "reportedDate": "2013-07-22",
                "reportedEPS": "0.29",
                "estimatedEPS": "0.34",
                "surprise": "-0.05",
                "surprisePercentage": "-14.7059",
            },
            {
                "fiscalDateEnding": "2013-03-31",
                "reportedDate": "2013-04-22",
                "reportedEPS": "0.05",
                "estimatedEPS": "0.04",
                "surprise": "0.01",
                "surprisePercentage": "25",
            },
            {
                "fiscalDateEnding": "2012-12-31",
                "reportedDate": "2013-02-07",
                "reportedEPS": "1.2",
                "estimatedEPS": "1.19",
                "surprise": "0.01",
                "surprisePercentage": "0.8403",
            },
            {
                "fiscalDateEnding": "2012-09-30",
                "reportedDate": "2012-10-22",
                "reportedEPS": "1.24",
                "estimatedEPS": "1.2",
                "surprise": "0.04",
                "surprisePercentage": "3.3333",
            },
            {
                "fiscalDateEnding": "2012-06-30",
                "reportedDate": "2012-07-23",
                "reportedEPS": "0.33",
                "estimatedEPS": "0.23",
                "surprise": "0.1",
                "surprisePercentage": "43.4783",
            },
            {
                "fiscalDateEnding": "2012-03-31",
                "reportedDate": "2012-04-23",
                "reportedEPS": "0.04",
                "estimatedEPS": "0.08",
                "surprise": "-0.04",
                "surprisePercentage": "-50",
            },
            {
                "fiscalDateEnding": "2011-12-31",
                "reportedDate": "2012-02-06",
                "reportedEPS": "1.06",
                "estimatedEPS": "1.05",
                "surprise": "0.01",
                "surprisePercentage": "0.9524",
            },
            {
                "fiscalDateEnding": "2011-09-30",
                "reportedDate": "2011-10-17",
                "reportedEPS": "1.27",
                "estimatedEPS": "1.3",
                "surprise": "-0.03",
                "surprisePercentage": "-2.3077",
            },
            {
                "fiscalDateEnding": "2011-06-30",
                "reportedDate": "2011-07-18",
                "reportedEPS": "0.33",
                "estimatedEPS": "0.39",
                "surprise": "-0.06",
                "surprisePercentage": "-15.3846",
            },
            {
                "fiscalDateEnding": "2011-03-31",
                "reportedDate": "2011-04-14",
                "reportedEPS": "0.12",
                "estimatedEPS": "0.17",
                "surprise": "-0.05",
                "surprisePercentage": "-29.4118",
            },
            {
                "fiscalDateEnding": "2010-12-31",
                "reportedDate": "2011-02-07",
                "reportedEPS": "0.99",
                "estimatedEPS": "0.92",
                "surprise": "0.07",
                "surprisePercentage": "7.6087",
            },
            {
                "fiscalDateEnding": "2010-09-30",
                "reportedDate": "2010-10-18",
                "reportedEPS": "1.09",
                "estimatedEPS": "1.04",
                "surprise": "0.05",
                "surprisePercentage": "4.8077",
            },
            {
                "fiscalDateEnding": "2010-06-30",
                "reportedDate": "2010-07-19",
                "reportedEPS": "0.29",
                "estimatedEPS": "0.24",
                "surprise": "0.05",
                "surprisePercentage": "20.8333",
            },
            {
                "fiscalDateEnding": "2010-03-31",
                "reportedDate": "2010-04-19",
                "reportedEPS": "0.26",
                "estimatedEPS": "0.16",
                "surprise": "0.1",
                "surprisePercentage": "62.5",
            },
            {
                "fiscalDateEnding": "2009-12-31",
                "reportedDate": "2010-02-08",
                "reportedEPS": "1.09",
                "estimatedEPS": "0.81",
                "surprise": "0.28",
                "surprisePercentage": "34.5679",
            },
            {
                "fiscalDateEnding": "2009-09-30",
                "reportedDate": "2009-10-19",
                "reportedEPS": "0.99",
                "estimatedEPS": "0.93",
                "surprise": "0.06",
                "surprisePercentage": "6.4516",
            },
            {
                "fiscalDateEnding": "2009-06-30",
                "reportedDate": "2009-07-20",
                "reportedEPS": "0.26",
                "estimatedEPS": "0.23",
                "surprise": "0.03",
                "surprisePercentage": "13.0435",
            },
            {
                "fiscalDateEnding": "2009-03-31",
                "reportedDate": "2009-04-20",
                "reportedEPS": "0.14",
                "estimatedEPS": "0.14",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2008-12-31",
                "reportedDate": "2009-02-09",
                "reportedEPS": "0.62",
                "estimatedEPS": "0.75",
                "surprise": "-0.13",
                "surprisePercentage": "-17.3333",
            },
            {
                "fiscalDateEnding": "2008-09-30",
                "reportedDate": "2008-10-20",
                "reportedEPS": "0.89",
                "estimatedEPS": "0.86",
                "surprise": "0.03",
                "surprisePercentage": "3.4884",
            },
            {
                "fiscalDateEnding": "2008-06-30",
                "reportedDate": "2008-07-21",
                "reportedEPS": "0.25",
                "estimatedEPS": "0.22",
                "surprise": "0.03",
                "surprisePercentage": "13.6364",
            },
            {
                "fiscalDateEnding": "2008-03-31",
                "reportedDate": "2008-04-21",
                "reportedEPS": "0.25",
                "estimatedEPS": "0.14",
                "surprise": "0.11",
                "surprisePercentage": "78.5714",
            },
            {
                "fiscalDateEnding": "2007-12-31",
                "reportedDate": "2008-02-11",
                "reportedEPS": "0.84",
                "estimatedEPS": "0.81",
                "surprise": "0.03",
                "surprisePercentage": "3.7037",
            },
            {
                "fiscalDateEnding": "2007-09-30",
                "reportedDate": "2007-10-22",
                "reportedEPS": "0.78",
                "estimatedEPS": "0.71",
                "surprise": "0.07",
                "surprisePercentage": "9.8592",
            },
            {
                "fiscalDateEnding": "2007-06-30",
                "reportedDate": "2007-07-23",
                "reportedEPS": "0.24",
                "estimatedEPS": "0.18",
                "surprise": "0.06",
                "surprisePercentage": "33.3333",
            },
            {
                "fiscalDateEnding": "2007-03-31",
                "reportedDate": "2007-04-23",
                "reportedEPS": "0.19",
                "estimatedEPS": "None",
                "surprise": "None",
                "surprisePercentage": "None",
            },
            {
                "fiscalDateEnding": "2006-12-31",
                "reportedDate": "2007-02-09",
                "reportedEPS": "0.62",
                "estimatedEPS": "0.67",
                "surprise": "-0.05",
                "surprisePercentage": "-7.4627",
            },
            {
                "fiscalDateEnding": "2006-09-30",
                "reportedDate": "2006-10-23",
                "reportedEPS": "0.58",
                "estimatedEPS": "0.5",
                "surprise": "0.08",
                "surprisePercentage": "16",
            },
            {
                "fiscalDateEnding": "2006-06-30",
                "reportedDate": "2006-07-24",
                "reportedEPS": "0.07",
                "estimatedEPS": "0.07",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2006-03-31",
                "reportedDate": "2006-04-24",
                "reportedEPS": "-0.03",
                "estimatedEPS": "-0.01",
                "surprise": "-0.02",
                "surprisePercentage": "-200",
            },
            {
                "fiscalDateEnding": "2005-12-31",
                "reportedDate": "2006-02-06",
                "reportedEPS": "0.61",
                "estimatedEPS": "0.58",
                "surprise": "0.03",
                "surprisePercentage": "5.1724",
            },
            {
                "fiscalDateEnding": "2005-09-30",
                "reportedDate": "2005-10-17",
                "reportedEPS": "0.47",
                "estimatedEPS": "0.51",
                "surprise": "-0.04",
                "surprisePercentage": "-7.8431",
            },
            {
                "fiscalDateEnding": "2005-06-30",
                "reportedDate": "2005-07-18",
                "reportedEPS": "0.13",
                "estimatedEPS": "0.08",
                "surprise": "0.05",
                "surprisePercentage": "62.5",
            },
            {
                "fiscalDateEnding": "2005-03-31",
                "reportedDate": "2005-04-18",
                "reportedEPS": "-0.02",
                "estimatedEPS": "0.04",
                "surprise": "-0.06",
                "surprisePercentage": "-150",
            },
            {
                "fiscalDateEnding": "2004-12-31",
                "reportedDate": "2005-02-07",
                "reportedEPS": "0.54",
                "estimatedEPS": "0.49",
                "surprise": "0.05",
                "surprisePercentage": "10.2041",
            },
            {
                "fiscalDateEnding": "2004-09-30",
                "reportedDate": "2004-10-18",
                "reportedEPS": "0.45",
                "estimatedEPS": "0.51",
                "surprise": "-0.06",
                "surprisePercentage": "-11.7647",
            },
            {
                "fiscalDateEnding": "2004-06-30",
                "reportedDate": "2004-07-16",
                "reportedEPS": "0.06",
                "estimatedEPS": "0.08",
                "surprise": "-0.02",
                "surprisePercentage": "-25",
            },
            {
                "fiscalDateEnding": "2004-03-31",
                "reportedDate": "2004-04-19",
                "reportedEPS": "0.03",
                "estimatedEPS": "0.03",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2003-12-31",
                "reportedDate": "2004-02-09",
                "reportedEPS": "0.65",
                "estimatedEPS": "0.55",
                "surprise": "0.1",
                "surprisePercentage": "18.1818",
            },
            {
                "fiscalDateEnding": "2003-09-30",
                "reportedDate": "2003-10-20",
                "reportedEPS": "0.48",
                "estimatedEPS": "0.42",
                "surprise": "0.06",
                "surprisePercentage": "14.2857",
            },
            {
                "fiscalDateEnding": "2003-06-30",
                "reportedDate": "2003-07-21",
                "reportedEPS": "0.06",
                "estimatedEPS": "0.04",
                "surprise": "0.02",
                "surprisePercentage": "50",
            },
            {
                "fiscalDateEnding": "2003-03-31",
                "reportedDate": "2003-04-21",
                "reportedEPS": "0.01",
                "estimatedEPS": "-0.06",
                "surprise": "0.07",
                "surprisePercentage": "116.6667",
            },
            {
                "fiscalDateEnding": "2002-12-31",
                "reportedDate": "2003-02-13",
                "reportedEPS": "0.42",
                "estimatedEPS": "0.38",
                "surprise": "0.04",
                "surprisePercentage": "10.5263",
            },
            {
                "fiscalDateEnding": "2002-09-30",
                "reportedDate": "2002-10-21",
                "reportedEPS": "0.32",
                "estimatedEPS": "0.37",
                "surprise": "-0.05",
                "surprisePercentage": "-13.5135",
            },
            {
                "fiscalDateEnding": "2002-06-30",
                "reportedDate": "2002-08-27",
                "reportedEPS": "-0.03",
                "estimatedEPS": "-0.06",
                "surprise": "0.03",
                "surprisePercentage": "50",
            },
            {
                "fiscalDateEnding": "2002-03-31",
                "reportedDate": "2002-04-22",
                "reportedEPS": "-0.1",
                "estimatedEPS": "-0.1",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2001-12-31",
                "reportedDate": "2002-02-07",
                "reportedEPS": "0.37",
                "estimatedEPS": "0.37",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2001-09-30",
                "reportedDate": "2001-10-22",
                "reportedEPS": "0.29",
                "estimatedEPS": "0.24",
                "surprise": "0.05",
                "surprisePercentage": "20.8333",
            },
            {
                "fiscalDateEnding": "2001-06-30",
                "reportedDate": "2001-07-23",
                "reportedEPS": "-0.11",
                "estimatedEPS": "-0.13",
                "surprise": "0.02",
                "surprisePercentage": "15.3846",
            },
            {
                "fiscalDateEnding": "2001-03-31",
                "reportedDate": "2001-04-23",
                "reportedEPS": "-0.14",
                "estimatedEPS": "-0.06",
                "surprise": "-0.08",
                "surprisePercentage": "-133.3333",
            },
            {
                "fiscalDateEnding": "2000-12-31",
                "reportedDate": "2001-02-08",
                "reportedEPS": "-0.34",
                "estimatedEPS": "-0.41",
                "surprise": "0.07",
                "surprisePercentage": "17.0732",
            },
            {
                "fiscalDateEnding": "2000-09-30",
                "reportedDate": "2000-10-19",
                "reportedEPS": "0.1",
                "estimatedEPS": "0.45",
                "surprise": "-0.35",
                "surprisePercentage": "-77.7778",
            },
            {
                "fiscalDateEnding": "2000-06-30",
                "reportedDate": "2000-07-20",
                "reportedEPS": "0.04",
                "estimatedEPS": "0.04",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2000-03-31",
                "reportedDate": "2000-04-25",
                "reportedEPS": "0.08",
                "estimatedEPS": "0.01",
                "surprise": "0.07",
                "surprisePercentage": "700",
            },
            {
                "fiscalDateEnding": "1999-12-31",
                "reportedDate": "2000-02-08",
                "reportedEPS": "0.79",
                "estimatedEPS": "0.74",
                "surprise": "0.05",
                "surprisePercentage": "6.7568",
            },
            {
                "fiscalDateEnding": "1999-09-30",
                "reportedDate": "1999-10-14",
                "reportedEPS": "0.43",
                "estimatedEPS": "0.43",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1999-06-30",
                "reportedDate": "1999-07-15",
                "reportedEPS": "0.16",
                "estimatedEPS": "0.1",
                "surprise": "0.06",
                "surprisePercentage": "60",
            },
            {
                "fiscalDateEnding": "1999-03-31",
                "reportedDate": "1999-04-15",
                "reportedEPS": "0.07",
                "estimatedEPS": "0.05",
                "surprise": "0.02",
                "surprisePercentage": "40",
            },
            {
                "fiscalDateEnding": "1998-12-31",
                "reportedDate": "1999-02-04",
                "reportedEPS": "0.65",
                "estimatedEPS": "0.63",
                "surprise": "0.02",
                "surprisePercentage": "3.1746",
            },
            {
                "fiscalDateEnding": "1998-09-30",
                "reportedDate": "1998-11-11",
                "reportedEPS": "0.37",
                "estimatedEPS": "0.37",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1998-06-30",
                "reportedDate": "1998-07-16",
                "reportedEPS": "0.03",
                "estimatedEPS": "0.02",
                "surprise": "0.01",
                "surprisePercentage": "50",
            },
            {
                "fiscalDateEnding": "1998-03-31",
                "reportedDate": "1998-04-16",
                "reportedEPS": "0.04",
                "estimatedEPS": "0.03",
                "surprise": "0.01",
                "surprisePercentage": "33.3333",
            },
            {
                "fiscalDateEnding": "1997-12-31",
                "reportedDate": "1998-02-05",
                "reportedEPS": "0.55",
                "estimatedEPS": "0.53",
                "surprise": "0.02",
                "surprisePercentage": "3.7736",
            },
            {
                "fiscalDateEnding": "1997-09-30",
                "reportedDate": "1997-10-20",
                "reportedEPS": "0.4",
                "estimatedEPS": "0.39",
                "surprise": "0.01",
                "surprisePercentage": "2.5641",
            },
            {
                "fiscalDateEnding": "1997-06-30",
                "reportedDate": "1997-07-17",
                "reportedEPS": "0.07",
                "estimatedEPS": "0.05",
                "surprise": "0.02",
                "surprisePercentage": "40",
            },
            {
                "fiscalDateEnding": "1997-03-31",
                "reportedDate": "1997-04-21",
                "reportedEPS": "0.13",
                "estimatedEPS": "0.13",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1996-12-31",
                "reportedDate": "1997-02-06",
                "reportedEPS": "0.5",
                "estimatedEPS": "0.5",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1996-09-30",
                "reportedDate": "1996-10-21",
                "reportedEPS": "0.36",
                "estimatedEPS": "0.36",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1996-06-30",
                "reportedDate": "1996-07-18",
                "reportedEPS": "0.03",
                "estimatedEPS": "0.03",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1996-03-31",
                "reportedDate": "1996-04-18",
                "reportedEPS": "0.12",
                "estimatedEPS": "0.12",
                "surprise": "0",
                "surprisePercentage": "0",
            },
        ],
    },
    {
        "symbol": "OMC",
        "quarterlyEarnings": [
            {
                "fiscalDateEnding": "2023-06-30",
                "reportedDate": "2023-07-18",
                "reportedEPS": "1.81",
                "estimatedEPS": "1.8",
                "surprise": "0.01",
                "surprisePercentage": "0.5556",
            },
            {
                "fiscalDateEnding": "2023-03-31",
                "reportedDate": "2023-04-18",
                "reportedEPS": "1.56",
                "estimatedEPS": "1.39",
                "surprise": "0.17",
                "surprisePercentage": "12.2302",
            },
            {
                "fiscalDateEnding": "2022-12-31",
                "reportedDate": "2023-02-07",
                "reportedEPS": "2.09",
                "estimatedEPS": "1.98",
                "surprise": "0.11",
                "surprisePercentage": "5.5556",
            },
            {
                "fiscalDateEnding": "2022-09-30",
                "reportedDate": "2022-10-18",
                "reportedEPS": "1.77",
                "estimatedEPS": "1.68",
                "surprise": "0.09",
                "surprisePercentage": "5.3571",
            },
            {
                "fiscalDateEnding": "2022-06-30",
                "reportedDate": "2022-07-19",
                "reportedEPS": "1.68",
                "estimatedEPS": "1.57",
                "surprise": "0.11",
                "surprisePercentage": "7.0064",
            },
            {
                "fiscalDateEnding": "2022-03-31",
                "reportedDate": "2022-04-19",
                "reportedEPS": "1.39",
                "estimatedEPS": "1.31",
                "surprise": "0.08",
                "surprisePercentage": "6.1069",
            },
            {
                "fiscalDateEnding": "2021-12-31",
                "reportedDate": "2022-02-08",
                "reportedEPS": "1.95",
                "estimatedEPS": "1.73",
                "surprise": "0.22",
                "surprisePercentage": "12.7168",
            },
            {
                "fiscalDateEnding": "2021-09-30",
                "reportedDate": "2021-10-19",
                "reportedEPS": "1.65",
                "estimatedEPS": "1.36",
                "surprise": "0.29",
                "surprisePercentage": "21.3235",
            },
            {
                "fiscalDateEnding": "2021-06-30",
                "reportedDate": "2021-07-20",
                "reportedEPS": "1.46",
                "estimatedEPS": "1.38",
                "surprise": "0.08",
                "surprisePercentage": "5.7971",
            },
            {
                "fiscalDateEnding": "2021-03-31",
                "reportedDate": "2021-04-20",
                "reportedEPS": "1.33",
                "estimatedEPS": "1.13",
                "surprise": "0.2",
                "surprisePercentage": "17.6991",
            },
            {
                "fiscalDateEnding": "2020-12-31",
                "reportedDate": "2021-02-18",
                "reportedEPS": "1.9",
                "estimatedEPS": "1.65",
                "surprise": "0.25",
                "surprisePercentage": "15.1515",
            },
            {
                "fiscalDateEnding": "2020-09-30",
                "reportedDate": "2020-10-27",
                "reportedEPS": "1.21",
                "estimatedEPS": "1.07",
                "surprise": "0.14",
                "surprisePercentage": "13.0841",
            },
            {
                "fiscalDateEnding": "2020-06-30",
                "reportedDate": "2020-07-28",
                "reportedEPS": "0.92",
                "estimatedEPS": "0.92",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2020-03-31",
                "reportedDate": "2020-04-28",
                "reportedEPS": "1.2",
                "estimatedEPS": "1.14",
                "surprise": "0.06",
                "surprisePercentage": "5.2632",
            },
            {
                "fiscalDateEnding": "2019-12-31",
                "reportedDate": "2020-02-11",
                "reportedEPS": "1.89",
                "estimatedEPS": "1.85",
                "surprise": "0.04",
                "surprisePercentage": "2.1622",
            },
            {
                "fiscalDateEnding": "2019-09-30",
                "reportedDate": "2019-10-15",
                "reportedEPS": "1.32",
                "estimatedEPS": "1.31",
                "surprise": "0.01",
                "surprisePercentage": "0.7634",
            },
            {
                "fiscalDateEnding": "2019-06-30",
                "reportedDate": "2019-07-17",
                "reportedEPS": "1.68",
                "estimatedEPS": "1.61",
                "surprise": "0.07",
                "surprisePercentage": "4.3478",
            },
            {
                "fiscalDateEnding": "2019-03-31",
                "reportedDate": "2019-04-16",
                "reportedEPS": "1.17",
                "estimatedEPS": "1.09",
                "surprise": "0.08",
                "surprisePercentage": "7.3394",
            },
            {
                "fiscalDateEnding": "2018-12-31",
                "reportedDate": "2019-02-12",
                "reportedEPS": "1.77",
                "estimatedEPS": "1.66",
                "surprise": "0.11",
                "surprisePercentage": "6.6265",
            },
            {
                "fiscalDateEnding": "2018-09-30",
                "reportedDate": "2018-10-16",
                "reportedEPS": "1.24",
                "estimatedEPS": "1.21",
                "surprise": "0.03",
                "surprisePercentage": "2.4793",
            },
            {
                "fiscalDateEnding": "2018-06-30",
                "reportedDate": "2018-07-17",
                "reportedEPS": "1.6",
                "estimatedEPS": "1.54",
                "surprise": "0.06",
                "surprisePercentage": "3.8961",
            },
            {
                "fiscalDateEnding": "2018-03-31",
                "reportedDate": "2018-04-17",
                "reportedEPS": "1.14",
                "estimatedEPS": "1.06",
                "surprise": "0.08",
                "surprisePercentage": "7.5472",
            },
            {
                "fiscalDateEnding": "2017-12-31",
                "reportedDate": "2018-02-15",
                "reportedEPS": "1.55",
                "estimatedEPS": "1.54",
                "surprise": "0.01",
                "surprisePercentage": "0.6494",
            },
            {
                "fiscalDateEnding": "2017-09-30",
                "reportedDate": "2017-10-17",
                "reportedEPS": "1.13",
                "estimatedEPS": "1.1",
                "surprise": "0.03",
                "surprisePercentage": "2.7273",
            },
            {
                "fiscalDateEnding": "2017-06-30",
                "reportedDate": "2017-07-20",
                "reportedEPS": "1.4",
                "estimatedEPS": "1.38",
                "surprise": "0.02",
                "surprisePercentage": "1.4493",
            },
            {
                "fiscalDateEnding": "2017-03-31",
                "reportedDate": "2017-04-18",
                "reportedEPS": "0.97",
                "estimatedEPS": "0.96",
                "surprise": "0.01",
                "surprisePercentage": "1.0417",
            },
            {
                "fiscalDateEnding": "2016-12-31",
                "reportedDate": "2017-02-07",
                "reportedEPS": "1.47",
                "estimatedEPS": "1.44",
                "surprise": "0.03",
                "surprisePercentage": "2.0833",
            },
            {
                "fiscalDateEnding": "2016-09-30",
                "reportedDate": "2016-10-18",
                "reportedEPS": "1.06",
                "estimatedEPS": "1.04",
                "surprise": "0.02",
                "surprisePercentage": "1.9231",
            },
            {
                "fiscalDateEnding": "2016-06-30",
                "reportedDate": "2016-07-14",
                "reportedEPS": "1.36",
                "estimatedEPS": "1.33",
                "surprise": "0.03",
                "surprisePercentage": "2.2556",
            },
            {
                "fiscalDateEnding": "2016-03-31",
                "reportedDate": "2016-04-19",
                "reportedEPS": "0.9",
                "estimatedEPS": "0.87",
                "surprise": "0.03",
                "surprisePercentage": "3.4483",
            },
            {
                "fiscalDateEnding": "2015-12-31",
                "reportedDate": "2016-02-09",
                "reportedEPS": "1.35",
                "estimatedEPS": "1.33",
                "surprise": "0.02",
                "surprisePercentage": "1.5038",
            },
            {
                "fiscalDateEnding": "2015-09-30",
                "reportedDate": "2015-10-20",
                "reportedEPS": "0.97",
                "estimatedEPS": "0.95",
                "surprise": "0.02",
                "surprisePercentage": "2.1053",
            },
            {
                "fiscalDateEnding": "2015-06-30",
                "reportedDate": "2015-07-21",
                "reportedEPS": "1.26",
                "estimatedEPS": "1.22",
                "surprise": "0.04",
                "surprisePercentage": "3.2787",
            },
            {
                "fiscalDateEnding": "2015-03-31",
                "reportedDate": "2015-04-21",
                "reportedEPS": "0.83",
                "estimatedEPS": "0.82",
                "surprise": "0.01",
                "surprisePercentage": "1.2195",
            },
            {
                "fiscalDateEnding": "2014-12-31",
                "reportedDate": "2015-02-10",
                "reportedEPS": "1.3",
                "estimatedEPS": "1.26",
                "surprise": "0.04",
                "surprisePercentage": "3.1746",
            },
            {
                "fiscalDateEnding": "2014-09-30",
                "reportedDate": "2014-10-21",
                "reportedEPS": "0.95",
                "estimatedEPS": "0.9",
                "surprise": "0.05",
                "surprisePercentage": "5.5556",
            },
            {
                "fiscalDateEnding": "2014-06-30",
                "reportedDate": "2014-07-22",
                "reportedEPS": "1.2",
                "estimatedEPS": "1.17",
                "surprise": "0.03",
                "surprisePercentage": "2.5641",
            },
            {
                "fiscalDateEnding": "2014-03-31",
                "reportedDate": "2014-04-22",
                "reportedEPS": "0.8",
                "estimatedEPS": "0.79",
                "surprise": "0.01",
                "surprisePercentage": "1.2658",
            },
            {
                "fiscalDateEnding": "2013-12-31",
                "reportedDate": "2014-02-11",
                "reportedEPS": "1.18",
                "estimatedEPS": "1.16",
                "surprise": "0.02",
                "surprisePercentage": "1.7241",
            },
            {
                "fiscalDateEnding": "2013-09-30",
                "reportedDate": "2013-10-15",
                "reportedEPS": "0.82",
                "estimatedEPS": "0.8",
                "surprise": "0.02",
                "surprisePercentage": "2.5",
            },
            {
                "fiscalDateEnding": "2013-06-30",
                "reportedDate": "2013-07-18",
                "reportedEPS": "1.09",
                "estimatedEPS": "1.08",
                "surprise": "0.01",
                "surprisePercentage": "0.9259",
            },
            {
                "fiscalDateEnding": "2013-03-31",
                "reportedDate": "2013-04-18",
                "reportedEPS": "0.76",
                "estimatedEPS": "0.75",
                "surprise": "0.01",
                "surprisePercentage": "1.3333",
            },
            {
                "fiscalDateEnding": "2012-12-31",
                "reportedDate": "2013-02-12",
                "reportedEPS": "1.13",
                "estimatedEPS": "1.09",
                "surprise": "0.04",
                "surprisePercentage": "3.6697",
            },
            {
                "fiscalDateEnding": "2012-09-30",
                "reportedDate": "2012-10-16",
                "reportedEPS": "0.74",
                "estimatedEPS": "0.72",
                "surprise": "0.02",
                "surprisePercentage": "2.7778",
            },
            {
                "fiscalDateEnding": "2012-06-30",
                "reportedDate": "2012-07-17",
                "reportedEPS": "1.02",
                "estimatedEPS": "1.01",
                "surprise": "0.01",
                "surprisePercentage": "0.9901",
            },
            {
                "fiscalDateEnding": "2012-03-31",
                "reportedDate": "2012-04-17",
                "reportedEPS": "0.72",
                "estimatedEPS": "0.69",
                "surprise": "0.03",
                "surprisePercentage": "4.3478",
            },
            {
                "fiscalDateEnding": "2011-12-31",
                "reportedDate": "2012-02-14",
                "reportedEPS": "0.96",
                "estimatedEPS": "0.95",
                "surprise": "0.01",
                "surprisePercentage": "1.0526",
            },
            {
                "fiscalDateEnding": "2011-09-30",
                "reportedDate": "2011-10-18",
                "reportedEPS": "0.72",
                "estimatedEPS": "0.7",
                "surprise": "0.02",
                "surprisePercentage": "2.8571",
            },
            {
                "fiscalDateEnding": "2011-06-30",
                "reportedDate": "2011-07-19",
                "reportedEPS": "0.96",
                "estimatedEPS": "0.92",
                "surprise": "0.04",
                "surprisePercentage": "4.3478",
            },
            {
                "fiscalDateEnding": "2011-03-31",
                "reportedDate": "2011-04-19",
                "reportedEPS": "0.69",
                "estimatedEPS": "0.59",
                "surprise": "0.1",
                "surprisePercentage": "16.9492",
            },
            {
                "fiscalDateEnding": "2010-12-31",
                "reportedDate": "2011-02-15",
                "reportedEPS": "0.83",
                "estimatedEPS": "0.81",
                "surprise": "0.02",
                "surprisePercentage": "2.4691",
            },
            {
                "fiscalDateEnding": "2010-09-30",
                "reportedDate": "2010-10-19",
                "reportedEPS": "0.57",
                "estimatedEPS": "0.58",
                "surprise": "-0.01",
                "surprisePercentage": "-1.7241",
            },
            {
                "fiscalDateEnding": "2010-06-30",
                "reportedDate": "2010-07-20",
                "reportedEPS": "0.79",
                "estimatedEPS": "0.77",
                "surprise": "0.02",
                "surprisePercentage": "2.5974",
            },
            {
                "fiscalDateEnding": "2010-03-31",
                "reportedDate": "2010-04-20",
                "reportedEPS": "0.52",
                "estimatedEPS": "0.5",
                "surprise": "0.02",
                "surprisePercentage": "4",
            },
            {
                "fiscalDateEnding": "2009-12-31",
                "reportedDate": "2010-02-10",
                "reportedEPS": "0.73",
                "estimatedEPS": "0.72",
                "surprise": "0.01",
                "surprisePercentage": "1.3889",
            },
            {
                "fiscalDateEnding": "2009-09-30",
                "reportedDate": "2009-10-21",
                "reportedEPS": "0.53",
                "estimatedEPS": "0.53",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2009-06-30",
                "reportedDate": "2009-07-23",
                "reportedEPS": "0.75",
                "estimatedEPS": "0.74",
                "surprise": "0.01",
                "surprisePercentage": "1.3514",
            },
            {
                "fiscalDateEnding": "2009-03-31",
                "reportedDate": "2009-04-27",
                "reportedEPS": "0.53",
                "estimatedEPS": "0.44",
                "surprise": "0.09",
                "surprisePercentage": "20.4545",
            },
            {
                "fiscalDateEnding": "2008-12-31",
                "reportedDate": "2009-02-10",
                "reportedEPS": "0.88",
                "estimatedEPS": "0.84",
                "surprise": "0.04",
                "surprisePercentage": "4.7619",
            },
            {
                "fiscalDateEnding": "2008-09-30",
                "reportedDate": "2008-10-21",
                "reportedEPS": "0.69",
                "estimatedEPS": "0.68",
                "surprise": "0.01",
                "surprisePercentage": "1.4706",
            },
            {
                "fiscalDateEnding": "2008-06-30",
                "reportedDate": "2008-07-22",
                "reportedEPS": "0.96",
                "estimatedEPS": "0.96",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2008-03-31",
                "reportedDate": "2008-04-22",
                "reportedEPS": "0.65",
                "estimatedEPS": "0.62",
                "surprise": "0.03",
                "surprisePercentage": "4.8387",
            },
            {
                "fiscalDateEnding": "2007-12-31",
                "reportedDate": "2008-02-12",
                "reportedEPS": "0.96",
                "estimatedEPS": "0.95",
                "surprise": "0.01",
                "surprisePercentage": "1.0526",
            },
            {
                "fiscalDateEnding": "2007-09-30",
                "reportedDate": "2007-10-23",
                "reportedEPS": "0.62",
                "estimatedEPS": "0.61",
                "surprise": "0.01",
                "surprisePercentage": "1.6393",
            },
            {
                "fiscalDateEnding": "2007-06-30",
                "reportedDate": "2007-07-24",
                "reportedEPS": "0.84",
                "estimatedEPS": "0.81",
                "surprise": "0.03",
                "surprisePercentage": "3.7037",
            },
            {
                "fiscalDateEnding": "2007-03-31",
                "reportedDate": "2007-04-24",
                "reportedEPS": "0.55",
                "estimatedEPS": "0.52",
                "surprise": "0.03",
                "surprisePercentage": "5.7692",
            },
            {
                "fiscalDateEnding": "2006-12-31",
                "reportedDate": "2007-02-13",
                "reportedEPS": "0.81",
                "estimatedEPS": "0.81",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2006-09-30",
                "reportedDate": "2006-10-24",
                "reportedEPS": "0.52",
                "estimatedEPS": "0.5",
                "surprise": "0.02",
                "surprisePercentage": "4",
            },
            {
                "fiscalDateEnding": "2006-06-30",
                "reportedDate": "2006-07-25",
                "reportedEPS": "0.71",
                "estimatedEPS": "0.69",
                "surprise": "0.02",
                "surprisePercentage": "2.8986",
            },
            {
                "fiscalDateEnding": "2006-03-31",
                "reportedDate": "2006-04-25",
                "reportedEPS": "0.47",
                "estimatedEPS": "0.45",
                "surprise": "0.02",
                "surprisePercentage": "4.4444",
            },
            {
                "fiscalDateEnding": "2005-12-31",
                "reportedDate": "2006-02-14",
                "reportedEPS": "0.71",
                "estimatedEPS": "0.71",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2005-09-30",
                "reportedDate": "2005-10-25",
                "reportedEPS": "0.45",
                "estimatedEPS": "0.43",
                "surprise": "0.02",
                "surprisePercentage": "4.6512",
            },
            {
                "fiscalDateEnding": "2005-06-30",
                "reportedDate": "2005-07-26",
                "reportedEPS": "0.62",
                "estimatedEPS": "0.62",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2005-03-31",
                "reportedDate": "2005-04-26",
                "reportedEPS": "0.41",
                "estimatedEPS": "0.4",
                "surprise": "0.01",
                "surprisePercentage": "2.5",
            },
            {
                "fiscalDateEnding": "2004-12-31",
                "reportedDate": "2005-02-22",
                "reportedEPS": "0.64",
                "estimatedEPS": "0.62",
                "surprise": "0.02",
                "surprisePercentage": "3.2258",
            },
            {
                "fiscalDateEnding": "2004-09-30",
                "reportedDate": "2004-10-26",
                "reportedEPS": "0.4",
                "estimatedEPS": "0.38",
                "surprise": "0.02",
                "surprisePercentage": "5.2632",
            },
            {
                "fiscalDateEnding": "2004-06-30",
                "reportedDate": "2004-07-27",
                "reportedEPS": "0.55",
                "estimatedEPS": "0.54",
                "surprise": "0.01",
                "surprisePercentage": "1.8519",
            },
            {
                "fiscalDateEnding": "2004-03-31",
                "reportedDate": "2004-04-27",
                "reportedEPS": "0.36",
                "estimatedEPS": "0.35",
                "surprise": "0.01",
                "surprisePercentage": "2.8571",
            },
            {
                "fiscalDateEnding": "2003-12-31",
                "reportedDate": "2004-02-17",
                "reportedEPS": "0.59",
                "estimatedEPS": "0.59",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2003-09-30",
                "reportedDate": "2003-10-28",
                "reportedEPS": "0.36",
                "estimatedEPS": "0.36",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2003-06-30",
                "reportedDate": "2003-07-29",
                "reportedEPS": "0.51",
                "estimatedEPS": "0.51",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2003-03-31",
                "reportedDate": "2003-04-29",
                "reportedEPS": "0.35",
                "estimatedEPS": "0.35",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2002-12-31",
                "reportedDate": "2003-02-25",
                "reportedEPS": "0.54",
                "estimatedEPS": "0.54",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2002-09-30",
                "reportedDate": "2002-10-29",
                "reportedEPS": "0.34",
                "estimatedEPS": "0.34",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2002-06-30",
                "reportedDate": "2002-08-06",
                "reportedEPS": "0.5",
                "estimatedEPS": "0.5",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2002-03-31",
                "reportedDate": "2002-04-30",
                "reportedEPS": "0.34",
                "estimatedEPS": "0.34",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2001-12-31",
                "reportedDate": "2002-02-19",
                "reportedEPS": "0.44",
                "estimatedEPS": "0.43",
                "surprise": "0.01",
                "surprisePercentage": "2.3256",
            },
            {
                "fiscalDateEnding": "2001-09-30",
                "reportedDate": "2001-10-23",
                "reportedEPS": "0.25",
                "estimatedEPS": "0.25",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2001-06-30",
                "reportedDate": "2001-07-24",
                "reportedEPS": "0.41",
                "estimatedEPS": "0.4",
                "surprise": "0.01",
                "surprisePercentage": "2.5",
            },
            {
                "fiscalDateEnding": "2001-03-31",
                "reportedDate": "2001-04-24",
                "reportedEPS": "0.27",
                "estimatedEPS": "0.25",
                "surprise": "0.02",
                "surprisePercentage": "8",
            },
            {
                "fiscalDateEnding": "2000-12-31",
                "reportedDate": "2001-02-20",
                "reportedEPS": "0.39",
                "estimatedEPS": "0.38",
                "surprise": "0.01",
                "surprisePercentage": "2.6316",
            },
            {
                "fiscalDateEnding": "2000-09-30",
                "reportedDate": "2000-10-24",
                "reportedEPS": "0.24",
                "estimatedEPS": "0.23",
                "surprise": "0.01",
                "surprisePercentage": "4.3478",
            },
            {
                "fiscalDateEnding": "2000-06-30",
                "reportedDate": "2000-07-25",
                "reportedEPS": "0.35",
                "estimatedEPS": "0.34",
                "surprise": "0.01",
                "surprisePercentage": "2.9412",
            },
            {
                "fiscalDateEnding": "2000-03-31",
                "reportedDate": "2000-04-25",
                "reportedEPS": "0.23",
                "estimatedEPS": "0.22",
                "surprise": "0.01",
                "surprisePercentage": "4.5455",
            },
            {
                "fiscalDateEnding": "1999-12-31",
                "reportedDate": "2000-02-22",
                "reportedEPS": "0.33",
                "estimatedEPS": "0.31",
                "surprise": "0.02",
                "surprisePercentage": "6.4516",
            },
            {
                "fiscalDateEnding": "1999-09-30",
                "reportedDate": "1999-10-21",
                "reportedEPS": "0.2",
                "estimatedEPS": "0.19",
                "surprise": "0.01",
                "surprisePercentage": "5.2632",
            },
            {
                "fiscalDateEnding": "1999-06-30",
                "reportedDate": "1999-07-22",
                "reportedEPS": "0.3",
                "estimatedEPS": "0.29",
                "surprise": "0.01",
                "surprisePercentage": "3.4483",
            },
            {
                "fiscalDateEnding": "1999-03-31",
                "reportedDate": "1999-04-22",
                "reportedEPS": "0.19",
                "estimatedEPS": "0.18",
                "surprise": "0.01",
                "surprisePercentage": "5.5556",
            },
            {
                "fiscalDateEnding": "1998-12-31",
                "reportedDate": "1999-02-18",
                "reportedEPS": "0.28",
                "estimatedEPS": "0.27",
                "surprise": "0.01",
                "surprisePercentage": "3.7037",
            },
            {
                "fiscalDateEnding": "1998-09-30",
                "reportedDate": "1998-10-22",
                "reportedEPS": "0.16",
                "estimatedEPS": "0.16",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1998-06-30",
                "reportedDate": "1998-07-23",
                "reportedEPS": "0.26",
                "estimatedEPS": "0.24",
                "surprise": "0.02",
                "surprisePercentage": "8.3333",
            },
            {
                "fiscalDateEnding": "1998-03-31",
                "reportedDate": "1998-04-23",
                "reportedEPS": "0.16",
                "estimatedEPS": "0.15",
                "surprise": "0.01",
                "surprisePercentage": "6.6667",
            },
            {
                "fiscalDateEnding": "1997-12-31",
                "reportedDate": "1998-02-19",
                "reportedEPS": "0.23",
                "estimatedEPS": "0.22",
                "surprise": "0.01",
                "surprisePercentage": "4.5455",
            },
            {
                "fiscalDateEnding": "1997-09-30",
                "reportedDate": "1997-10-23",
                "reportedEPS": "0.13",
                "estimatedEPS": "0.12",
                "surprise": "0.01",
                "surprisePercentage": "8.3333",
            },
            {
                "fiscalDateEnding": "1997-06-30",
                "reportedDate": "1997-07-24",
                "reportedEPS": "0.2",
                "estimatedEPS": "0.2",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1997-03-31",
                "reportedDate": "1997-04-24",
                "reportedEPS": "0.13",
                "estimatedEPS": "0.12",
                "surprise": "0.01",
                "surprisePercentage": "8.3333",
            },
            {
                "fiscalDateEnding": "1996-12-31",
                "reportedDate": "1997-02-20",
                "reportedEPS": "0.19",
                "estimatedEPS": "0.18",
                "surprise": "0.01",
                "surprisePercentage": "5.5556",
            },
            {
                "fiscalDateEnding": "1996-09-30",
                "reportedDate": "1996-10-24",
                "reportedEPS": "0.11",
                "estimatedEPS": "0.1",
                "surprise": "0.01",
                "surprisePercentage": "10",
            },
            {
                "fiscalDateEnding": "1996-06-30",
                "reportedDate": "1996-07-25",
                "reportedEPS": "0.17",
                "estimatedEPS": "0.16",
                "surprise": "0.01",
                "surprisePercentage": "6.25",
            },
            {
                "fiscalDateEnding": "1996-03-31",
                "reportedDate": "1996-04-25",
                "reportedEPS": "0.1",
                "estimatedEPS": "0.1",
                "surprise": "0",
                "surprisePercentage": "0",
            },
        ],
    },
    {
        "symbol": "SCHW",
        "quarterlyEarnings": [
            {
                "fiscalDateEnding": "2023-09-30",
                "reportedDate": "2023-10-16",
                "reportedEPS": "None",
                "estimatedEPS": "0.74",
                "surprise": "None",
                "surprisePercentage": "None",
            },
            {
                "fiscalDateEnding": "2023-06-30",
                "reportedDate": "2023-07-18",
                "reportedEPS": "0.75",
                "estimatedEPS": "0.71",
                "surprise": "0.04",
                "surprisePercentage": "5.6338",
            },
            {
                "fiscalDateEnding": "2023-03-31",
                "reportedDate": "2023-04-17",
                "reportedEPS": "0.93",
                "estimatedEPS": "0.9",
                "surprise": "0.03",
                "surprisePercentage": "3.3333",
            },
            {
                "fiscalDateEnding": "2022-12-31",
                "reportedDate": "2023-01-18",
                "reportedEPS": "1.09",
                "estimatedEPS": "1.09",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2022-09-30",
                "reportedDate": "2022-10-17",
                "reportedEPS": "1.1",
                "estimatedEPS": "1.05",
                "surprise": "0.05",
                "surprisePercentage": "4.7619",
            },
            {
                "fiscalDateEnding": "2022-06-30",
                "reportedDate": "2022-07-18",
                "reportedEPS": "0.97",
                "estimatedEPS": "0.91",
                "surprise": "0.06",
                "surprisePercentage": "6.5934",
            },
            {
                "fiscalDateEnding": "2022-03-31",
                "reportedDate": "2022-04-18",
                "reportedEPS": "0.77",
                "estimatedEPS": "0.84",
                "surprise": "-0.07",
                "surprisePercentage": "-8.3333",
            },
            {
                "fiscalDateEnding": "2021-12-31",
                "reportedDate": "2022-01-18",
                "reportedEPS": "0.86",
                "estimatedEPS": "0.88",
                "surprise": "-0.02",
                "surprisePercentage": "-2.2727",
            },
            {
                "fiscalDateEnding": "2021-09-30",
                "reportedDate": "2021-10-15",
                "reportedEPS": "0.84",
                "estimatedEPS": "0.81",
                "surprise": "0.03",
                "surprisePercentage": "3.7037",
            },
            {
                "fiscalDateEnding": "2021-06-30",
                "reportedDate": "2021-07-16",
                "reportedEPS": "0.8",
                "estimatedEPS": "0.71",
                "surprise": "0.09",
                "surprisePercentage": "12.6761",
            },
            {
                "fiscalDateEnding": "2021-03-31",
                "reportedDate": "2021-04-15",
                "reportedEPS": "0.84",
                "estimatedEPS": "0.82",
                "surprise": "0.02",
                "surprisePercentage": "2.439",
            },
            {
                "fiscalDateEnding": "2020-12-31",
                "reportedDate": "2021-01-19",
                "reportedEPS": "0.74",
                "estimatedEPS": "0.71",
                "surprise": "0.03",
                "surprisePercentage": "4.2254",
            },
            {
                "fiscalDateEnding": "2020-09-30",
                "reportedDate": "2020-10-15",
                "reportedEPS": "0.48",
                "estimatedEPS": "0.46",
                "surprise": "0.02",
                "surprisePercentage": "4.3478",
            },
            {
                "fiscalDateEnding": "2020-06-30",
                "reportedDate": "2020-07-16",
                "reportedEPS": "0.48",
                "estimatedEPS": "0.53",
                "surprise": "-0.05",
                "surprisePercentage": "-9.434",
            },
            {
                "fiscalDateEnding": "2020-03-31",
                "reportedDate": "2020-04-15",
                "reportedEPS": "0.58",
                "estimatedEPS": "0.62",
                "surprise": "-0.04",
                "surprisePercentage": "-6.4516",
            },
            {
                "fiscalDateEnding": "2019-12-31",
                "reportedDate": "2020-01-16",
                "reportedEPS": "0.63",
                "estimatedEPS": "0.64",
                "surprise": "-0.01",
                "surprisePercentage": "-1.5625",
            },
            {
                "fiscalDateEnding": "2019-09-30",
                "reportedDate": "2019-10-15",
                "reportedEPS": "0.74",
                "estimatedEPS": "0.64",
                "surprise": "0.1",
                "surprisePercentage": "15.625",
            },
            {
                "fiscalDateEnding": "2019-06-30",
                "reportedDate": "2019-07-16",
                "reportedEPS": "0.66",
                "estimatedEPS": "0.65",
                "surprise": "0.01",
                "surprisePercentage": "1.5385",
            },
            {
                "fiscalDateEnding": "2019-03-31",
                "reportedDate": "2019-04-15",
                "reportedEPS": "0.69",
                "estimatedEPS": "0.66",
                "surprise": "0.03",
                "surprisePercentage": "4.5455",
            },
            {
                "fiscalDateEnding": "2018-12-31",
                "reportedDate": "2019-01-16",
                "reportedEPS": "0.65",
                "estimatedEPS": "0.64",
                "surprise": "0.01",
                "surprisePercentage": "1.5625",
            },
            {
                "fiscalDateEnding": "2018-09-30",
                "reportedDate": "2018-10-15",
                "reportedEPS": "0.65",
                "estimatedEPS": "0.65",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2018-06-30",
                "reportedDate": "2018-07-17",
                "reportedEPS": "0.6",
                "estimatedEPS": "0.58",
                "surprise": "0.02",
                "surprisePercentage": "3.4483",
            },
            {
                "fiscalDateEnding": "2018-03-31",
                "reportedDate": "2018-04-16",
                "reportedEPS": "0.55",
                "estimatedEPS": "0.54",
                "surprise": "0.01",
                "surprisePercentage": "1.8519",
            },
            {
                "fiscalDateEnding": "2017-12-31",
                "reportedDate": "2018-01-17",
                "reportedEPS": "0.44",
                "estimatedEPS": "0.41",
                "surprise": "0.03",
                "surprisePercentage": "7.3171",
            },
            {
                "fiscalDateEnding": "2017-09-30",
                "reportedDate": "2017-10-16",
                "reportedEPS": "0.42",
                "estimatedEPS": "0.41",
                "surprise": "0.01",
                "surprisePercentage": "2.439",
            },
            {
                "fiscalDateEnding": "2017-06-30",
                "reportedDate": "2017-07-18",
                "reportedEPS": "0.39",
                "estimatedEPS": "0.39",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2017-03-31",
                "reportedDate": "2017-04-18",
                "reportedEPS": "0.39",
                "estimatedEPS": "0.36",
                "surprise": "0.03",
                "surprisePercentage": "8.3333",
            },
            {
                "fiscalDateEnding": "2016-12-31",
                "reportedDate": "2017-01-18",
                "reportedEPS": "0.36",
                "estimatedEPS": "0.36",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2016-09-30",
                "reportedDate": "2016-10-17",
                "reportedEPS": "0.34",
                "estimatedEPS": "0.33",
                "surprise": "0.01",
                "surprisePercentage": "3.0303",
            },
            {
                "fiscalDateEnding": "2016-06-30",
                "reportedDate": "2016-07-18",
                "reportedEPS": "0.3",
                "estimatedEPS": "0.3",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2016-03-31",
                "reportedDate": "2016-04-15",
                "reportedEPS": "0.29",
                "estimatedEPS": "0.29",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2015-12-31",
                "reportedDate": "2016-01-19",
                "reportedEPS": "0.24",
                "estimatedEPS": "0.25",
                "surprise": "-0.01",
                "surprisePercentage": "-4",
            },
            {
                "fiscalDateEnding": "2015-09-30",
                "reportedDate": "2015-10-15",
                "reportedEPS": "0.27",
                "estimatedEPS": "0.27",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2015-06-30",
                "reportedDate": "2015-07-16",
                "reportedEPS": "0.25",
                "estimatedEPS": "0.24",
                "surprise": "0.01",
                "surprisePercentage": "4.1667",
            },
            {
                "fiscalDateEnding": "2015-03-31",
                "reportedDate": "2015-04-15",
                "reportedEPS": "0.22",
                "estimatedEPS": "0.24",
                "surprise": "-0.02",
                "surprisePercentage": "-8.3333",
            },
            {
                "fiscalDateEnding": "2014-12-31",
                "reportedDate": "2015-01-16",
                "reportedEPS": "0.24",
                "estimatedEPS": "0.24",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2014-09-30",
                "reportedDate": "2014-10-15",
                "reportedEPS": "0.24",
                "estimatedEPS": "0.24",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2014-06-30",
                "reportedDate": "2014-07-16",
                "reportedEPS": "0.23",
                "estimatedEPS": "0.22",
                "surprise": "0.01",
                "surprisePercentage": "4.5455",
            },
            {
                "fiscalDateEnding": "2014-03-31",
                "reportedDate": "2014-04-15",
                "reportedEPS": "0.24",
                "estimatedEPS": "0.22",
                "surprise": "0.02",
                "surprisePercentage": "9.0909",
            },
            {
                "fiscalDateEnding": "2013-12-31",
                "reportedDate": "2014-01-16",
                "reportedEPS": "0.23",
                "estimatedEPS": "0.21",
                "surprise": "0.02",
                "surprisePercentage": "9.5238",
            },
            {
                "fiscalDateEnding": "2013-09-30",
                "reportedDate": "2013-10-15",
                "reportedEPS": "0.22",
                "estimatedEPS": "0.2",
                "surprise": "0.02",
                "surprisePercentage": "10",
            },
            {
                "fiscalDateEnding": "2013-06-30",
                "reportedDate": "2013-07-16",
                "reportedEPS": "0.18",
                "estimatedEPS": "0.19",
                "surprise": "-0.01",
                "surprisePercentage": "-5.2632",
            },
            {
                "fiscalDateEnding": "2013-03-31",
                "reportedDate": "2013-04-15",
                "reportedEPS": "0.15",
                "estimatedEPS": "0.16",
                "surprise": "-0.01",
                "surprisePercentage": "-6.25",
            },
            {
                "fiscalDateEnding": "2012-12-31",
                "reportedDate": "2013-01-16",
                "reportedEPS": "0.15",
                "estimatedEPS": "0.15",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2012-09-30",
                "reportedDate": "2012-10-15",
                "reportedEPS": "0.17",
                "estimatedEPS": "0.17",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2012-06-30",
                "reportedDate": "2012-07-17",
                "reportedEPS": "0.2",
                "estimatedEPS": "0.18",
                "surprise": "0.02",
                "surprisePercentage": "11.1111",
            },
            {
                "fiscalDateEnding": "2012-03-31",
                "reportedDate": "2012-04-16",
                "reportedEPS": "0.15",
                "estimatedEPS": "0.15",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2011-12-31",
                "reportedDate": "2012-01-18",
                "reportedEPS": "0.13",
                "estimatedEPS": "0.13",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2011-09-30",
                "reportedDate": "2011-10-17",
                "reportedEPS": "0.19",
                "estimatedEPS": "0.19",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2011-06-30",
                "reportedDate": "2011-07-18",
                "reportedEPS": "0.2",
                "estimatedEPS": "0.19",
                "surprise": "0.01",
                "surprisePercentage": "5.2632",
            },
            {
                "fiscalDateEnding": "2011-03-31",
                "reportedDate": "2011-04-15",
                "reportedEPS": "0.2",
                "estimatedEPS": "0.19",
                "surprise": "0.01",
                "surprisePercentage": "5.2632",
            },
            {
                "fiscalDateEnding": "2010-12-31",
                "reportedDate": "2011-01-18",
                "reportedEPS": "0.1",
                "estimatedEPS": "0.1",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2010-09-30",
                "reportedDate": "2010-10-15",
                "reportedEPS": "0.1",
                "estimatedEPS": "0.09",
                "surprise": "0.01",
                "surprisePercentage": "11.1111",
            },
            {
                "fiscalDateEnding": "2010-06-30",
                "reportedDate": "2010-07-16",
                "reportedEPS": "0.17",
                "estimatedEPS": "0.15",
                "surprise": "0.02",
                "surprisePercentage": "13.3333",
            },
            {
                "fiscalDateEnding": "2010-03-31",
                "reportedDate": "2010-04-15",
                "reportedEPS": "0.1",
                "estimatedEPS": "0.11",
                "surprise": "-0.01",
                "surprisePercentage": "-9.0909",
            },
            {
                "fiscalDateEnding": "2009-12-31",
                "reportedDate": "2010-01-19",
                "reportedEPS": "0.14",
                "estimatedEPS": "0.15",
                "surprise": "-0.01",
                "surprisePercentage": "-6.6667",
            },
            {
                "fiscalDateEnding": "2009-09-30",
                "reportedDate": "2009-10-15",
                "reportedEPS": "0.17",
                "estimatedEPS": "0.17",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2009-06-30",
                "reportedDate": "2009-07-16",
                "reportedEPS": "0.18",
                "estimatedEPS": "0.18",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2009-03-31",
                "reportedDate": "2009-04-15",
                "reportedEPS": "0.19",
                "estimatedEPS": "0.15",
                "surprise": "0.04",
                "surprisePercentage": "26.6667",
            },
            {
                "fiscalDateEnding": "2008-12-31",
                "reportedDate": "2009-01-16",
                "reportedEPS": "0.27",
                "estimatedEPS": "0.26",
                "surprise": "0.01",
                "surprisePercentage": "3.8462",
            },
            {
                "fiscalDateEnding": "2008-09-30",
                "reportedDate": "2008-10-15",
                "reportedEPS": "0.26",
                "estimatedEPS": "0.23",
                "surprise": "0.03",
                "surprisePercentage": "13.0435",
            },
            {
                "fiscalDateEnding": "2008-06-30",
                "reportedDate": "2008-07-16",
                "reportedEPS": "0.27",
                "estimatedEPS": "0.26",
                "surprise": "0.01",
                "surprisePercentage": "3.8462",
            },
            {
                "fiscalDateEnding": "2008-03-31",
                "reportedDate": "2008-04-15",
                "reportedEPS": "0.26",
                "estimatedEPS": "0.26",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2007-12-31",
                "reportedDate": "2008-01-16",
                "reportedEPS": "0.26",
                "estimatedEPS": "0.27",
                "surprise": "-0.01",
                "surprisePercentage": "-3.7037",
            },
            {
                "fiscalDateEnding": "2007-09-30",
                "reportedDate": "2007-10-15",
                "reportedEPS": "0.27",
                "estimatedEPS": "0.25",
                "surprise": "0.02",
                "surprisePercentage": "8",
            },
            {
                "fiscalDateEnding": "2007-06-30",
                "reportedDate": "2007-07-17",
                "reportedEPS": "0.23",
                "estimatedEPS": "0.23",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2007-03-31",
                "reportedDate": "2007-04-17",
                "reportedEPS": "0.22",
                "estimatedEPS": "0.22",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2006-12-31",
                "reportedDate": "2007-01-17",
                "reportedEPS": "0.21",
                "estimatedEPS": "0.21",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2006-09-30",
                "reportedDate": "2006-10-16",
                "reportedEPS": "0.21",
                "estimatedEPS": "0.2",
                "surprise": "0.01",
                "surprisePercentage": "5",
            },
            {
                "fiscalDateEnding": "2006-06-30",
                "reportedDate": "2006-07-18",
                "reportedEPS": "0.19",
                "estimatedEPS": "0.2",
                "surprise": "-0.01",
                "surprisePercentage": "-5",
            },
            {
                "fiscalDateEnding": "2006-03-31",
                "reportedDate": "2006-04-17",
                "reportedEPS": "0.19",
                "estimatedEPS": "0.19",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2005-12-31",
                "reportedDate": "2006-01-18",
                "reportedEPS": "0.14",
                "estimatedEPS": "0.14",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2005-09-30",
                "reportedDate": "2005-10-17",
                "reportedEPS": "0.16",
                "estimatedEPS": "0.15",
                "surprise": "0.01",
                "surprisePercentage": "6.6667",
            },
            {
                "fiscalDateEnding": "2005-06-30",
                "reportedDate": "2005-07-18",
                "reportedEPS": "0.14",
                "estimatedEPS": "0.13",
                "surprise": "0.01",
                "surprisePercentage": "7.6923",
            },
            {
                "fiscalDateEnding": "2005-03-31",
                "reportedDate": "2005-04-15",
                "reportedEPS": "0.12",
                "estimatedEPS": "0.12",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2004-12-31",
                "reportedDate": "2005-01-18",
                "reportedEPS": "0.12",
                "estimatedEPS": "0.11",
                "surprise": "0.01",
                "surprisePercentage": "9.0909",
            },
            {
                "fiscalDateEnding": "2004-09-30",
                "reportedDate": "2004-10-15",
                "reportedEPS": "0.08",
                "estimatedEPS": "0.08",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2004-06-30",
                "reportedDate": "2004-07-20",
                "reportedEPS": "0.08",
                "estimatedEPS": "0.09",
                "surprise": "-0.01",
                "surprisePercentage": "-11.1111",
            },
            {
                "fiscalDateEnding": "2004-03-31",
                "reportedDate": "2004-04-20",
                "reportedEPS": "0.12",
                "estimatedEPS": "0.12",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2003-12-31",
                "reportedDate": "2004-01-22",
                "reportedEPS": "0.11",
                "estimatedEPS": "0.11",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2003-09-30",
                "reportedDate": "2003-10-21",
                "reportedEPS": "0.11",
                "estimatedEPS": "0.1",
                "surprise": "0.01",
                "surprisePercentage": "10",
            },
            {
                "fiscalDateEnding": "2003-06-30",
                "reportedDate": "2003-07-23",
                "reportedEPS": "0.09",
                "estimatedEPS": "0.09",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2003-03-31",
                "reportedDate": "2003-04-22",
                "reportedEPS": "0.05",
                "estimatedEPS": "0.05",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2002-12-31",
                "reportedDate": "2003-01-21",
                "reportedEPS": "0.07",
                "estimatedEPS": "0.08",
                "surprise": "-0.01",
                "surprisePercentage": "-12.5",
            },
            {
                "fiscalDateEnding": "2002-09-30",
                "reportedDate": "2002-10-15",
                "reportedEPS": "0.07",
                "estimatedEPS": "0.07",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2002-06-30",
                "reportedDate": "2002-07-16",
                "reportedEPS": "0.07",
                "estimatedEPS": "0.08",
                "surprise": "-0.01",
                "surprisePercentage": "-12.5",
            },
            {
                "fiscalDateEnding": "2002-03-31",
                "reportedDate": "2002-04-16",
                "reportedEPS": "0.08",
                "estimatedEPS": "0.08",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2001-12-31",
                "reportedDate": "2002-01-15",
                "reportedEPS": "0.08",
                "estimatedEPS": "0.08",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2001-09-30",
                "reportedDate": "2001-10-16",
                "reportedEPS": "0.06",
                "estimatedEPS": "0.05",
                "surprise": "0.01",
                "surprisePercentage": "20",
            },
            {
                "fiscalDateEnding": "2001-06-30",
                "reportedDate": "2001-07-17",
                "reportedEPS": "0.07",
                "estimatedEPS": "0.08",
                "surprise": "-0.01",
                "surprisePercentage": "-12.5",
            },
            {
                "fiscalDateEnding": "2001-03-31",
                "reportedDate": "2001-04-17",
                "reportedEPS": "0.08",
                "estimatedEPS": "0.08",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2000-12-31",
                "reportedDate": "2001-01-18",
                "reportedEPS": "0.11",
                "estimatedEPS": "0.12",
                "surprise": "-0.01",
                "surprisePercentage": "-8.3333",
            },
            {
                "fiscalDateEnding": "2000-09-30",
                "reportedDate": "2000-10-17",
                "reportedEPS": "0.12",
                "estimatedEPS": "0.12",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "2000-06-30",
                "reportedDate": "2000-07-18",
                "reportedEPS": "0.14",
                "estimatedEPS": "0.15",
                "surprise": "-0.01",
                "surprisePercentage": "-6.6667",
            },
            {
                "fiscalDateEnding": "2000-03-31",
                "reportedDate": "2000-04-17",
                "reportedEPS": "0.22",
                "estimatedEPS": "0.22",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1999-12-31",
                "reportedDate": "2000-01-18",
                "reportedEPS": "0.13",
                "estimatedEPS": "0.13",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1999-09-30",
                "reportedDate": "1999-10-14",
                "reportedEPS": "0.1",
                "estimatedEPS": "0.1",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1999-06-30",
                "reportedDate": "1999-07-16",
                "reportedEPS": "0.12",
                "estimatedEPS": "0.11",
                "surprise": "0.01",
                "surprisePercentage": "9.0909",
            },
            {
                "fiscalDateEnding": "1999-03-31",
                "reportedDate": "1999-04-15",
                "reportedEPS": "0.12",
                "estimatedEPS": "0.11",
                "surprise": "0.01",
                "surprisePercentage": "9.0909",
            },
            {
                "fiscalDateEnding": "1998-12-31",
                "reportedDate": "1999-01-19",
                "reportedEPS": "0.09",
                "estimatedEPS": "0.08",
                "surprise": "0.01",
                "surprisePercentage": "12.5",
            },
            {
                "fiscalDateEnding": "1998-09-30",
                "reportedDate": "1998-10-15",
                "reportedEPS": "0.08",
                "estimatedEPS": "0.07",
                "surprise": "0.01",
                "surprisePercentage": "14.2857",
            },
            {
                "fiscalDateEnding": "1998-06-30",
                "reportedDate": "1998-07-16",
                "reportedEPS": "0.06",
                "estimatedEPS": "0.06",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1998-03-31",
                "reportedDate": "1998-04-15",
                "reportedEPS": "0.06",
                "estimatedEPS": "0.06",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1997-12-31",
                "reportedDate": "1998-01-14",
                "reportedEPS": "0.06",
                "estimatedEPS": "0.06",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1997-09-30",
                "reportedDate": "1997-10-15",
                "reportedEPS": "0.06",
                "estimatedEPS": "0.06",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1997-06-30",
                "reportedDate": "1997-07-16",
                "reportedEPS": "0.05",
                "estimatedEPS": "0.05",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1997-03-31",
                "reportedDate": "1997-04-16",
                "reportedEPS": "0.05",
                "estimatedEPS": "0.05",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1996-12-31",
                "reportedDate": "1997-01-16",
                "reportedEPS": "0.05",
                "estimatedEPS": "0.05",
                "surprise": "0",
                "surprisePercentage": "0",
            },
            {
                "fiscalDateEnding": "1996-09-30",
                "reportedDate": "1996-10-11",
                "reportedEPS": "0.05",
                "estimatedEPS": "0.04",
                "surprise": "0.01",
                "surprisePercentage": "25",
            },
            {
                "fiscalDateEnding": "1996-06-30",
                "reportedDate": "1996-07-17",
                "reportedEPS": "0.06",
                "estimatedEPS": "0.04",
                "surprise": "0.02",
                "surprisePercentage": "50",
            },
            {
                "fiscalDateEnding": "1996-03-31",
                "reportedDate": "1996-04-16",
                "reportedEPS": "0.04",
                "estimatedEPS": "0.04",
                "surprise": "0",
                "surprisePercentage": "0",
            },
        ],
    },
]

df = pd.DataFrame(mylist)

# Extract latest quarterly earnings from the list of dictionaries
df["latestQuarterlyEarnings"] = df["quarterlyEarnings"].apply(
    lambda x: x[0]["reportedEPS"]
)
# Extract surprise from the list of dictionaries
df["surprise"] = df["quarterlyEarnings"].apply(lambda x: x[0]["surprise"])
# Extract surprisePercentage from the list of dictionaries
df["surprisePercentage"] = df["quarterlyEarnings"].apply(
    lambda x: x[0]["surprisePercentage"]
)
# Extract fiscalDateEnding and estimated EPS from the list of dictionaries
df["fiscalDateEnding"] = df["quarterlyEarnings"].apply(
    lambda x: x[0]["fiscalDateEnding"]
)
df["estimatedEPS"] = df["quarterlyEarnings"].apply(lambda x: x[0]["estimatedEPS"])
